# Generated by Django 5.0.3 on 2024-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50, verbose_name='Member Name')),
                ('add_date', models.DateField(verbose_name='Add date')),
                ('about_member', models.TextField(verbose_name='About Member')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='News Title')),
                ('content', models.TextField(verbose_name='News Content')),
                ('news_date', models.DateField(auto_now_add=True, verbose_name='News Date')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
            ],
        ),
    ]
