# Generated by Django 5.0.3 on 2024-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0002_news_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_image',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Member Image'),
        ),
    ]
